name: example
description: "OAuth VK ID example"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.3.8 # Windows/Linux/macOS app window size controller
  webview_flutter: ^4.4.3 # Mobile OS webview provider
  desktop_webview_window: ^0.2.3

  vk_id:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
