name: vk_id
description: Dart module with VK ID OAuth API functions. The module allows to log in using VK ID API and receive an access token and user data
version: 1.0.3
homepage: https://github.com/mIwr/vkid-dart-sdk
repository: https://github.com/mIwr/vkid-dart-sdk

false_secrets:
  - /test/test_constants.dart

topics:
  - network
  - oauth
  - vk-id

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.0.0
  crypto: ^3.0.3

dev_dependencies:
  lints: any
  test: ^1.24.4
